package com.netflix.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;

@Service
@Slf4j
public class WhisperService {

    @Value("${python.path:py}")
    private String pythonPath;

    @Value("${whisper.model:base}")
    private String model;

    @Value("${whisper.language:en}")
    private String language;

    public File generateSubtitles(File audioFile, String outputDir) throws Exception {
        if (!audioFile.exists()) {
            throw new RuntimeException("Audio file not found: " + audioFile.getAbsolutePath());
        }

        // Ensure output directory exists
        Files.createDirectories(Paths.get(outputDir));

        log.info("========== WHISPER ==========");
        log.info("Audio     : {}", audioFile.getAbsolutePath());
        log.info("OutputDir : {}", outputDir);
        log.info("Python    : {}", pythonPath);
        log.info("Model     : {}", model);
        log.info("Language  : {}", language);

        // Get the base name of the audio file (without extension)
        String audioBaseName = audioFile.getName().replaceAll("\\.[^.]+$", "");
        File expectedSubtitleFile = new File(outputDir, audioBaseName + ".srt");

        // Delete old subtitle file if it exists
        if (expectedSubtitleFile.exists()) {
            expectedSubtitleFile.delete();
        }

        // Build command
        ProcessBuilder builder = new ProcessBuilder(
                pythonPath,
                "-m",
                "whisper",
                audioFile.getAbsolutePath(),
                "--model",
                model,
                "--language",
                language,
                "--output_dir",
                outputDir,
                "--output_format",
                "srt"
        );

        builder.redirectErrorStream(true);
        log.info("Command: {}", String.join(" ", builder.command()));

        Process process = builder.start();

        // Read and log output in real-time
        StringBuilder output = new StringBuilder();
        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(process.getInputStream()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                log.info("[WHISPER] {}", line);
                output.append(line).append("\n");
            }
        }

        int exit = process.waitFor();
        log.info("Whisper Exit Code : {}", exit);

        if (exit != 0) {
            log.error("Whisper error output:\n{}", output.toString());
            throw new RuntimeException("Whisper failed with exit code: " + exit);
        }

        // Wait a moment for file to be written
        Thread.sleep(1000);

        // Find the generated SRT file
        File dir = new File(outputDir);
        File[] subtitleFiles = dir.listFiles((d, name) -> name.toLowerCase().endsWith(".srt"));

        if (subtitleFiles == null || subtitleFiles.length == 0) {
            log.error("No .srt file found in {}", outputDir);
            log.error("Directory contents:");
            File[] allFiles = dir.listFiles();
            if (allFiles != null) {
                for (File f : allFiles) {
                    log.info("  - {} ({} bytes)", f.getName(), f.length());
                }
            }
            throw new RuntimeException("No .srt file generated by Whisper.");
        }

        // Log all subtitle files found
        for (File f : subtitleFiles) {
            log.info("Found subtitle file: {} ({} bytes)", f.getName(), f.length());
        }

        // Use the first subtitle file found
        File sourceSubtitle = subtitleFiles[0];
        File finalSubtitle = new File(outputDir, "subtitle.srt");

        // If the source is already subtitle.srt, we're done
        if (sourceSubtitle.getName().equals("subtitle.srt")) {
            log.info("Subtitle already exists: {}", sourceSubtitle.getAbsolutePath());
            return sourceSubtitle;
        }

        // Rename to subtitle.srt
        Files.move(sourceSubtitle.toPath(), finalSubtitle.toPath(),
                StandardCopyOption.REPLACE_EXISTING);

        log.info("Subtitle created: {} (size: {} bytes)",
                finalSubtitle.getAbsolutePath(), finalSubtitle.length());

        return finalSubtitle;
    }
}