spring:
  application:
    name: encoding-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: encoding-service-group-v2
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.netflix.event.VideoUploadedEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket: netflix-videos

ffmpeg:
  path: ${FFMPEG_PATH:D:/ffmpeg-8.1.2-essentials_build/ffmpeg-8.1.2-essentials_build/bin/ffmpeg.exe}

encoding:
  base-path: ${ENCODING_BASE_PATH:D:/temp2/encoding}

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info